version: "3"
services:
  db:
    # TODO: Set up your database image, we recommend one of these:
    image: mongo:4
    volumes:
      - ./db-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: fastfood
      MONGO_INITDB_ROOT_PASSWORD: secretpswd
    restart: always
    ports: # Expose the db container port 27017 to the host machine 28017
      - 28017:27017 # para conectar con compass que esta instalado en my host
    networks: 
      - private # Connect the service to the 'private' network
      - public # Connect the service to the 'public' network
    
  node:
    image: node:18 # https://hub.docker.com/_/node/
    user: node
    working_dir: /home/node/app
    environment:
      NODE_ENV: production
      PORT: 8080
      DB_URL: mongodb://fastfood:secretpswd@db:27017/defftonesdb?authSource=admin
      JWT_SECRET: qotsa
      ADMIN_EMAIL: admin@localhost
      ADMIN_PASSWORD: 9999
    volumes:
      - ./:/home/node/app # Mount the code in the home directory of the user '_node_'
    ports: # Expose the node container port 8080 to port 80 of our machine
      - 80:8080
    expose:
      - 8080 # Our app runs on port 8080
    # Reinstall dependencies and start the server
    command: bash -c 'rm -rf node_modules && npm install && npm start'
    depends_on:
      - db
    networks:
      - public
      - private
networks:
  public:
    internal: false
  private:
    internal: true
